#General Parameters
base_frame: base_footprint
map_update_interval: 2.0 # Defautl 5.0
resolution: 0.01 # degfault: 0.05
delta: 0.01 # default: 0.05 - Needs to be the same as resolution

use_scan_matching: true # In real cases always set to true, in simulation sometimes the matching can create more error
use_scan_barycenter: true

minimum_travel_distance: 0.12
minimum_travel_heading: 0.174

scan_buffer_size: 70
scan_buffer_maximum_scan_distance: 3.5 # default 20.0

link_match_minimum_response_fine: 0.12
link_scan_maximum_distance: 3.5

loop_search_maximum_distance: 3.5
do_loop_closing: true
loop_match_minimum_chain_size: 10
loop_match_maximum_variance_coarse: 0.4
loop_match_minimum_response_coarse: 0.8
loop_match_minimum_response_fine: 0.8


# Corelation parameters - Correlation Parameters
correlation_search_space_dimension: 0.3
correlation_search_space_resolution: 0.01
correlation_search_space_smear_deviation: 0.03

# Corelation parameters - Loop Closure parameters
loop_search_space_dimension: 8.0
loop_search_space_resolution: 0.05
loop_search_space_smear_deviation: 0.03

# Scan Matcher Paramenters
distance_variance_penalty: 0.3
angle_variance_penalty: 0.349
fine_search_angle_offset: 0.00349
coarse_search_angle_offset: 0.349
coarse_angle_resolution: 0.0349
minimum_angle_penalty: 0.9
minimum_distance_penalty: 0.5
use_response_expansion: false